/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Dez extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dez.class.getName());

    /**
     * Creates new form Dez
     */
    public Dez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Unidades de Área");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setLineWrap(false);
        jTextArea1.setWrapStyleWord(false);
        jTextArea1.setText("Digite um valor em m²");
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Converter");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        lbl1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 255));
        lbl1.setText("0");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("m²");

        jLabel2.setText("Ainda em uso");

        lbl2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 255));
        lbl2.setText("0");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("dulum (дулум) da Bósnia, Herzegovina e Sérvia");

        lbl3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 255));
        lbl3.setText("0");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("dynym ou dylym da Albânia");

        lbl4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 255));
        lbl4.setText("0");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("donum do Chipre");

        lbl5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 255));
        lbl5.setText("0");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("skales (σκάλες) do Chipre");

        lbl6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 255));
        lbl6.setText("0");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("stremma grega");

        lbl7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 255));
        lbl7.setText("0");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("stremma turca da Grécia");

        lbl8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 0, 255));
        lbl8.setText("0");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("dunam do Iraque");

        lbl9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 0, 255));
        lbl9.setText("0");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("dunam (dönüm, دونم) da Turquia, Síria, Israel, Palestina, Jordânia, Líbano");

        lbl10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 255));
        lbl10.setText("0");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("dunam (dönüm, دونم) antigo (anterior a 1928) da Turquia, Síria, Israel, Palestina, Jordânia, Líbano");

        lbl11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 0, 255));
        lbl11.setText("0");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("feddan (فدّان) do Egito, Sudão, Síria, Omã");

        lbl12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 0, 255));
        lbl12.setText("0");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("kirat (قيراط) do Egito");

        lbl13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl13.setForeground(new java.awt.Color(0, 0, 255));
        lbl13.setText("0");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("manzana da Argentina");

        lbl14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl14.setForeground(new java.awt.Color(0, 0, 255));
        lbl14.setText("0");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("manzana da Belize");

        lbl15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl15.setForeground(new java.awt.Color(0, 0, 255));
        lbl15.setText("0");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("manzana da Costa Rica");

        lbl16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl16.setForeground(new java.awt.Color(0, 0, 255));
        lbl16.setText("0");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("manzana da Guatemala");

        lbl17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl17.setForeground(new java.awt.Color(0, 0, 255));
        lbl17.setText("0");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("manzana da Honduras");

        lbl18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl18.setForeground(new java.awt.Color(0, 0, 255));
        lbl18.setText("0");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("manzana da Nicarágua");

        lbl19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl19.setForeground(new java.awt.Color(0, 0, 255));
        lbl19.setText("0");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("cuadra da Argentina");

        lbl20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl20.setForeground(new java.awt.Color(0, 0, 255));
        lbl20.setText("0");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setText("cuadra do Chile");

        lbl21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl21.setForeground(new java.awt.Color(0, 0, 255));
        lbl21.setText("0");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("cuadra do Equador");

        lbl22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl22.setForeground(new java.awt.Color(0, 0, 255));
        lbl22.setText("0");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 0, 0));
        jLabel40.setText("cuadra do Paraguai");

        lbl23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl23.setForeground(new java.awt.Color(0, 0, 255));
        lbl23.setText("0");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("cuadra do Peru");

        lbl24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl24.setForeground(new java.awt.Color(0, 0, 255));
        lbl24.setText("0");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("cuadra do Uruguai");

        lbl25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl25.setForeground(new java.awt.Color(0, 0, 255));
        lbl25.setText("0");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("vara quadrada do Panamá e da Colômbia");

        lbl26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl26.setForeground(new java.awt.Color(0, 0, 255));
        lbl26.setText("0");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 0, 0));
        jLabel44.setText("vara quadrada do Chile, Costa Rica, República Dominicana, Equador, El Salvador, Guatemala, Honduras, México, Nicarágua, Peru, São Tomé e Príncipe, Venezuela");

        lbl27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl27.setForeground(new java.awt.Color(0, 0, 255));
        lbl27.setText("0");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 0, 0));
        jLabel45.setText("vara quadrada de Cuba");

        lbl28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl28.setForeground(new java.awt.Color(0, 0, 255));
        lbl28.setText("0");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 0, 0));
        jLabel46.setText("vara quadrada da Argentina, Paraguai, Uruguai");

        lbl29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl29.setForeground(new java.awt.Color(0, 0, 255));
        lbl29.setText("0");

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 0, 0));
        jLabel47.setText("vara quadrada do Brasil");

        javax.swing.JPanel mainPanel = new javax.swing.JPanel();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22)))
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl16)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel37)))
                                .addGap(158, 158, 158)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl28)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl27)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl26)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel44))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl25)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel43))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl24)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel42))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl23)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl22)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl20)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl29)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel47))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(539, 539, 539)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(626, 626, 626)
                                .addComponent(lbl1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(jLabel20)
                    .addComponent(lbl11)
                    .addComponent(jLabel29)
                    .addComponent(lbl20)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(jLabel21)
                    .addComponent(lbl12)
                    .addComponent(jLabel30)
                    .addComponent(lbl21)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4)
                    .addComponent(jLabel22)
                    .addComponent(lbl13)
                    .addComponent(jLabel31)
                    .addComponent(lbl22)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5)
                    .addComponent(jLabel23)
                    .addComponent(lbl14)
                    .addComponent(jLabel32)
                    .addComponent(lbl23)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl6)
                    .addComponent(jLabel24)
                    .addComponent(lbl15)
                    .addComponent(jLabel33)
                    .addComponent(lbl24)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl7)
                    .addComponent(jLabel25)
                    .addComponent(lbl16)
                    .addComponent(jLabel34)
                    .addComponent(lbl25)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8)
                    .addComponent(jLabel26)
                    .addComponent(lbl17)
                    .addComponent(jLabel35)
                    .addComponent(lbl26)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl9)
                    .addComponent(jLabel27)
                    .addComponent(lbl18)
                    .addComponent(jLabel36)
                    .addComponent(lbl27)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl10)
                    .addComponent(jLabel28)
                    .addComponent(lbl19)
                    .addComponent(jLabel37)
                    .addComponent(lbl28)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl29)
                    .addComponent(jLabel47))
                .addContainerGap())
        );

        javax.swing.JScrollPane mainScrollPane = new javax.swing.JScrollPane(mainPanel);
        mainScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        mainScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        setContentPane(mainScrollPane);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float a = Integer.parseInt(jTextArea1.getText());
        float cx = a / 1000;
        float cy = a / 1000;
        float cz = a * 2446 / 1000000;
        float da = a / 1000;
        float db = a / 1000;
        float dc = a * 7874 / 10000000;
        float dd = a * 4 / 10000;
        float de = a / 1000;
        float df = a * 1088 / 1000000;
        float dg = a * 2381 / 10000000;
        float dh = a * 5714 / 1000000;
        float di = a / 10000;
        float dj = a * 1197 / 10000000;
        float dk = a * 1431 / 10000000;
        float dl = a * 1417 / 10000000;
        float dm = a * 1434 / 10000000;
        float dn = a * 1429 / 10000000;
        float doo = a * 5928 / 100000000;
        float dp = a * 6359 / 100000000;
        float dq = a * 1417 / 10000000;
        float dr = a * 1333 / 10000000;
        float ds = a / 10000;
        float dt = a * 1355 / 10000000;
        float du = a * 1563 / 1000;
        float dv = a * 1417 / 1000;
        float dw = a * 1391 / 1000;
        float dx = a * 1336 / 1000;
        float dy = a * 8264 / 10000;
        lbl1.setText(Float.toString(a));
        lbl2.setText(Float.toString(cx));
        lbl3.setText(Float.toString(cy));
        lbl4.setText(Float.toString(cz));
        lbl5.setText(Float.toString(da));
        lbl6.setText(Float.toString(db));
        lbl7.setText(Float.toString(dc));
        lbl8.setText(Float.toString(dd));
        lbl9.setText(Float.toString(de));
        lbl10.setText(Float.toString(df));
        lbl11.setText(Float.toString(dg));
        lbl12.setText(Float.toString(dh));
        lbl13.setText(Float.toString(di));
        lbl14.setText(Float.toString(dj));
        lbl15.setText(Float.toString(dk));
        lbl16.setText(Float.toString(dl));
        lbl17.setText(Float.toString(dm));
        lbl18.setText(Float.toString(dn));
        lbl19.setText(Float.toString(doo));
        lbl20.setText(Float.toString(dp));
        lbl21.setText(Float.toString(dq));
        lbl22.setText(Float.toString(dr));
        lbl23.setText(Float.toString(ds));
        lbl24.setText(Float.toString(dt));
        lbl25.setText(Float.toString(du));
        lbl26.setText(Float.toString(dv));
        lbl27.setText(Float.toString(dw));
        lbl28.setText(Float.toString(dx));
        lbl29.setText(Float.toString(dy));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dez().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables
}
