/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anton
 */
public class Velocidade extends javax.swing.JFrame {

    /**
     * Creates new form Velocidade
     */
    public Velocidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblAB = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAD = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblAE = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblH = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblJ = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblK = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblL = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblQ = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lblR = new javax.swing.JLabel();
        lblS = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        lblW = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblZ = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        lblV = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        lblAA = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Medidas Métricas");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("EUA e Inglaterra");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ritmo");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Unidades Náuticas");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Física");

        jLabel6.setText("nó");

        jLabel7.setText("milha marítima por hora");

        lblAC.setForeground(new java.awt.Color(0, 0, 255));
        lblAC.setText("jLabel8");

        lblAB.setForeground(new java.awt.Color(0, 0, 255));
        lblAB.setText("jLabel9");

        jLabel10.setText("velocidade do som no ar");

        lblAD.setForeground(new java.awt.Color(0, 0, 255));
        lblAD.setText("jLabel11");

        jLabel12.setText("velocidade da luz no vácuo");

        lblAE.setForeground(new java.awt.Color(0, 0, 255));
        lblAE.setText("jLabel13");

        jLabel14.setText("km/s");

        lblA.setForeground(new java.awt.Color(0, 0, 255));
        lblA.setText("jLabel15");

        jLabel16.setText("m/s");

        lblB.setForeground(new java.awt.Color(0, 0, 255));
        lblB.setText("jLabel17");

        jLabel18.setText("quilômetro por minuto");

        jLabel19.setText("metro por minuto");

        lblC.setForeground(new java.awt.Color(0, 0, 255));
        lblC.setText("jLabel20");

        lblD.setForeground(new java.awt.Color(0, 0, 255));
        lblD.setText("jLabel21");

        jLabel22.setText("km/h");

        lblE.setForeground(new java.awt.Color(0, 0, 255));
        lblE.setText("jLabel23");

        jLabel24.setText("m/h");

        lblF.setForeground(new java.awt.Color(0, 0, 255));
        lblF.setText("jLabel25");

        jTextArea1.setBackground(new java.awt.Color(180, 180, 180));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(90, 90, 90));
        jTextArea1.setRows(5);
        jTextArea1.setText("Digite um valor em km/h:");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel26.setText("quilômetro por ano");

        lblG.setForeground(new java.awt.Color(0, 0, 255));
        lblG.setText("jLabel27");

        jLabel28.setText("metro por ano");

        lblH.setForeground(new java.awt.Color(0, 0, 255));
        lblH.setText("jLabel29");

        lblI.setForeground(new java.awt.Color(0, 0, 255));
        lblI.setText("jLabel30");

        jLabel31.setText("milha por segundo");

        jLabel32.setText("pé por segundo");

        lblJ.setForeground(new java.awt.Color(0, 0, 255));
        lblJ.setText("jLabel33");

        jLabel34.setText("polegada por segundo");

        lblK.setForeground(new java.awt.Color(0, 0, 255));
        lblK.setText("jLabel35");

        jLabel36.setText("milha por minuto");

        lblL.setForeground(new java.awt.Color(0, 0, 255));
        lblL.setText("jLabel37");

        jLabel38.setText("pé por minuto");

        lblM.setForeground(new java.awt.Color(0, 0, 255));
        lblM.setText("jLabel39");

        jLabel40.setText("polegada por minuto");

        lblN.setForeground(new java.awt.Color(0, 0, 255));
        lblN.setText("jLabel41");

        jLabel42.setText("mph");

        lblO.setForeground(new java.awt.Color(0, 0, 255));
        lblO.setText("jLabel43");

        jLabel44.setText("pé por hora");

        lblP.setForeground(new java.awt.Color(0, 0, 255));
        lblP.setText("jLabel45");

        lblQ.setForeground(new java.awt.Color(0, 0, 255));
        lblQ.setText("jLabel46");

        jLabel47.setText("polegada por hora");

        jLabel48.setText("milha por ano");

        lblR.setForeground(new java.awt.Color(0, 0, 255));
        lblR.setText("jLabel49");

        lblS.setForeground(new java.awt.Color(0, 0, 255));
        lblS.setText("jLabel50");

        jLabel51.setText("pé por ano");

        jLabel52.setText("polegada por amo");

        lblT.setForeground(new java.awt.Color(0, 0, 255));
        lblT.setText("jLabel53");

        lblU.setForeground(new java.awt.Color(0, 0, 255));
        lblU.setText("jLabel54");

        jLabel55.setText("minutos por quilômetro");

        jLabel56.setText("segundos por 100 metros");

        lblW.setForeground(new java.awt.Color(0, 0, 255));
        lblW.setText("jLabel57");

        jLabel58.setText("segundos por milha");

        lblY.setForeground(new java.awt.Color(0, 0, 255));
        lblY.setText("jLabel59");

        lblZ.setForeground(new java.awt.Color(0, 0, 255));
        lblZ.setText("jLabel60");

        jLabel61.setText("segundos por 100 jardas");

        lblX.setForeground(new java.awt.Color(0, 0, 255));
        lblX.setText("jLabel62");

        jLabel63.setText("minutos por milha");

        lblV.setForeground(new java.awt.Color(0, 0, 255));
        lblV.setText("jLabel64");

        jLabel65.setText("segundos por quilômetro");

        jLabel66.setText("segundos por 500 metros");

        lblAA.setForeground(new java.awt.Color(0, 0, 255));
        lblAA.setText("jLabel67");

        jButton1.setText("Converter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAB)
                    .addComponent(lblAD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblAC)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lblAE)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblA)))
                                        .addGap(87, 87, 87)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblC)
                                            .addComponent(lblD)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(265, 265, 265)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel56)
                                                .addComponent(jLabel63))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblW)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblX)
                                                    .addGap(6, 6, 6))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(114, 114, 114)
                                            .addComponent(jLabel26)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblG)
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel28)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblH))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(259, 259, 259)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblI))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblJ))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblK))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel55)
                                                    .addComponent(jLabel65))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblU)
                                                    .addComponent(lblV)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblL)))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel38)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblM))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel40)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblN)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel44)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblP))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel42)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblO)))
                                                .addGap(56, 56, 56)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel51)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel47))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQ)
                                    .addComponent(lblS)
                                    .addComponent(lblR)
                                    .addComponent(lblT)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel58))
                                    .addComponent(jLabel61))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblY)
                                    .addComponent(lblZ)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblE)
                                    .addComponent(lblF))))))
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblA)
                    .addComponent(jLabel18)
                    .addComponent(lblC)
                    .addComponent(jLabel22)
                    .addComponent(lblE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblB)
                    .addComponent(jLabel19)
                    .addComponent(lblD)
                    .addComponent(jLabel24)
                    .addComponent(lblF))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblG)
                    .addComponent(jLabel28)
                    .addComponent(lblH))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblI)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(lblJ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(lblK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(lblL)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(lblM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(lblN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel42)
                                    .addComponent(lblO))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44)
                                    .addComponent(lblP))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblU)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)
                            .addComponent(lblW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX)
                            .addComponent(jLabel63)
                            .addComponent(lblV)
                            .addComponent(jLabel65)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQ)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(lblR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(lblT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(lblY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZ)
                            .addComponent(jLabel61))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(lblAA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblAC)
                    .addComponent(lblAB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblAD)
                    .addComponent(jLabel12)
                    .addComponent(lblAE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float a = Integer.parseInt(jTextArea1.getText());
        float b = a / 10000000 * 2778;
        float c = a / 10000 * 2778;
        float d = a / 100000 * 1667;
        float e = a / 100 * 1667;
        float f = a;
        float g = a * 1000;
        float h = a * 8766;
        float i = a * 8765813;
        float j = a / 10000000 * 1726;
        float k = a / 10000 * 9113;
        float l = a / 100 * 1094;
        float m = a / 100000 * 1036;
        float n = a / 100 * 5468;
        float o = a / 10 * 6562;
        float p = a / 10000 * 6214;
        float q = a * 3281;
        float r = a * 39370;
        float s = a * 5447;
        float t = a * 28759228;
        float u = a * 345110740;
        float v = a * 60 / f / f;
        float w = a * 3600 / f / f;
        float xis = a * 360 / f / f;
        float ypsilon = a / 100 * 9656 / f / f;
        float z = a * 5794 / f / f;
        float aa = a / 10 * 3292 / f / f;
        float ab = a * 1800 / f / f;
        float ac = a / 100 * 54;
        float ad = a / 100 * 54;
        float ae = a / 1000000 * 817;
        float af = a / 1000000 / 1000000 * 926;
        lblA.setText(Float.toString(b));
        lblB.setText(Float.toString(c));
        lblC.setText(Float.toString(d));
        lblD.setText(Float.toString(e));
        lblE.setText(Float.toString(f));
        lblF.setText(Float.toString(g));
        lblG.setText(Float.toString(h));
        lblH.setText(Float.toString(i));
        lblI.setText(Float.toString(j));
        lblJ.setText(Float.toString(k));
        lblK.setText(Float.toString(l));
        lblL.setText(Float.toString(m));
        lblM.setText(Float.toString(n));
        lblN.setText(Float.toString(o));
        lblO.setText(Float.toString(p));
        lblP.setText(Float.toString(q));
        lblQ.setText(Float.toString(r));
        lblR.setText(Float.toString(s));
        lblS.setText(Float.toString(t));
        lblT.setText(Float.toString(u));
        lblU.setText(Float.toString(v));
        lblV.setText(Float.toString(w));
        lblW.setText(Float.toString(xis));
        lblX.setText(Float.toString(ypsilon));
        lblY.setText(Float.toString(z));
        lblZ.setText(Float.toString(aa));
        lblAA.setText(Float.toString(ab));
        lblAB.setText(Float.toString(ac));
        lblAC.setText(Float.toString(ad));
        lblAD.setText(Float.toString(ae));
        lblAE.setText(Float.toString(af));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Velocidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Velocidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Velocidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Velocidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Velocidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAA;
    private javax.swing.JLabel lblAB;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblAD;
    private javax.swing.JLabel lblAE;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblJ;
    private javax.swing.JLabel lblK;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lblR;
    private javax.swing.JLabel lblS;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblU;
    private javax.swing.JLabel lblV;
    private javax.swing.JLabel lblW;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel lblZ;
    // End of variables declaration//GEN-END:variables
}
